"""
email_service.py — Email notification system using smtplib
Credentials are read from environment variables: MAIL_USERNAME and MAIL_PASSWORD
Set EMAIL_DEV_MODE=true in .env to print emails to console instead of sending.
"""
import os
import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

MAIL_USERNAME = os.getenv("MAIL_USERNAME", "")
MAIL_PASSWORD = os.getenv("MAIL_PASSWORD", "")
EMAIL_DEV_MODE = os.getenv("EMAIL_DEV_MODE", "true").lower() == "true"


# ── Core sender ────────────────────────────────────────────────────────────

def send_email(to_email: str, subject: str, message: str) -> bool:
    """
    Send an HTML email.
    Returns True on success, False on failure.
    In dev-mode (EMAIL_DEV_MODE=true) the email is printed to the console only.
    """
    if EMAIL_DEV_MODE:
        _print_dev_email(to_email, subject, message)
        return True

    if not MAIL_USERNAME or not MAIL_PASSWORD:
        print("[!] Email credentials not set. Enable EMAIL_DEV_MODE or set MAIL_USERNAME/MAIL_PASSWORD in .env")
        return False

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = MAIL_USERNAME
        msg["To"] = to_email

        html_body = _wrap_html(subject, message)
        msg.attach(MIMEText(message, "plain"))
        msg.attach(MIMEText(html_body, "html"))

        context = ssl.create_default_context()
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
            server.login(MAIL_USERNAME, MAIL_PASSWORD)
            server.sendmail(MAIL_USERNAME, to_email, msg.as_string())
        print(f"[OK] Email sent to {to_email}: {subject}")
        return True
    except Exception as e:
        print(f"[FAIL] Email failed — {e}")
        return False


def _print_dev_email(to_email, subject, message):
    separator = "-" * 60
    print(f"\n{separator}")
    print(f"[DEV EMAIL] To: {to_email}")
    print(f"Subject : {subject}")
    print(f"Message :\n{message}")
    print(f"{separator}\n")


def _wrap_html(subject, plain_text):
    """Wrap plain text in a simple but styled HTML email template."""
    body_html = plain_text.replace("\n", "<br>")
    return f"""
    <!DOCTYPE html>
    <html>
    <body style="font-family:Arial,sans-serif;background:#f4f4f4;padding:20px;">
      <div style="max-width:600px;margin:auto;background:white;border-radius:12px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.1);">
        <div style="background:linear-gradient(135deg,#00b09b,#96c93d);padding:30px;text-align:center;">
          <h2 style="color:white;margin:0;">🏥 AI Health Assistant</h2>
        </div>
        <div style="padding:30px;">
          <h3 style="color:#333;">{subject}</h3>
          <p style="color:#555;line-height:1.7;">{body_html}</p>
          <hr style="margin:20px 0;border:none;border-top:1px solid #eee;">
          <p style="color:#999;font-size:12px;text-align:center;">
            This is an automated notification from AI Health Assistant.<br>
            <strong>Note:</strong> AI predictions are for informational purposes only and are not a confirmed medical diagnosis.
          </p>
        </div>
      </div>
    </body>
    </html>
    """


# ── Pre-built email templates ──────────────────────────────────────────────

def send_registration_email(to_email: str, user_name: str) -> bool:
    subject = "Welcome to AI Health Assistant"
    message = f"""Hello {user_name},

Your registration with AI Powered Health Assistant has been completed successfully.

You can now use:
  • Health Profile Management
  • Symptom Analysis
  • AI Disease Prediction
  • Precaution Recommendations
  • Lifestyle Recommendations
  • AI Health Chat
  • Chat With Doctor
  • Appointment Booking

Thank you for trusting AI Health Assistant with your health journey.

Stay healthy!
— The AI Health Assistant Team"""
    return send_email(to_email, subject, message)


def send_prediction_email(to_email: str, user_name: str, disease: str,
                          confidence: float, precautions: list, lifestyle: list) -> bool:
    subject = "AI Health Prediction Result"
    prec_text = "\n".join(f"  • {p}" for p in precautions)
    life_text = "\n".join(f"  • l" for l in lifestyle)
    life_text = "\n".join(f"  • {l}" for l in lifestyle)
    message = f"""Hello {user_name},

Your symptom analysis has been completed.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Possible Disease : {disease}
Prediction Confidence : {confidence:.1f}%
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Recommended Precautions:
{prec_text}

Lifestyle Recommendations:
{life_text}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
⚠️ IMPORTANT DISCLAIMER:
This result is generated by an AI system and is NOT a confirmed medical diagnosis.
Please consult a qualified healthcare professional if symptoms persist, worsen, or concern you.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Stay safe,
— AI Health Assistant"""
    return send_email(to_email, subject, message)


def send_doctor_message_notification(doctor_email: str, doctor_name: str,
                                     patient_name: str) -> bool:
    subject = "New Patient Message — AI Health Assistant"
    message = f"""Hello Dr. {doctor_name},

You have received a new message from your patient {patient_name} on AI Health Assistant.

Please login to your Doctor Dashboard to read and reply to the message.

— AI Health Assistant"""
    return send_email(doctor_email, subject, message)


def send_doctor_reply_notification(patient_email: str, patient_name: str,
                                   doctor_name: str) -> bool:
    subject = "Your Doctor Has Replied — AI Health Assistant"
    message = f"""Hello {patient_name},

Dr. {doctor_name} has replied to your health message.

Please login to AI Health Assistant to view the response.

— AI Health Assistant"""
    return send_email(patient_email, subject, message)


def send_appointment_confirmation(to_email: str, patient_name: str, doctor_name: str,
                                  appt_date: str, appt_time: str, reason: str) -> bool:
    subject = "Doctor Appointment Confirmation — AI Health Assistant"
    doc_display = doctor_name if doctor_name.startswith("Dr.") else f"Dr. {doctor_name}"
    message = f"""Hello {patient_name},

Your appointment has been successfully booked!

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Doctor Name     : {doc_display}
Appointment Date: {appt_date}
Appointment Time: {appt_time}
Reason          : {reason}
Status          : Confirmed
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Please arrive 10 minutes before your scheduled time.

— AI Health Assistant"""
    return send_email(to_email, subject, message)


def send_health_alert(to_email: str, user_name: str, alert_message: str) -> bool:
    subject = "⚠️ Health Alert — AI Health Assistant"
    message = f"""Hello {user_name},

{alert_message}

Please consult a qualified healthcare professional as soon as possible.

— AI Health Assistant"""
    return send_email(to_email, subject, message)


def send_ambulance_alert_email(
    to_email: str,
    patient_name: str,
    patient_age: str,
    mobile_number: str,
    area_location: str,
    emergency_reason: str,
    maps_url: str,
    ambulance_id: str = "AMB-108"
) -> bool:
    subject = "🚨 URGENT: Emergency Ambulance Dispatched — AI Health Assistant"
    message = f"""EMERGENCY AMBULANCE DISPATCH NOTIFICATION

Patient Information:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Patient Name    : {patient_name}
Patient Age     : {patient_age} years
Contact Mobile  : {mobile_number}
Area / Address  : {area_location}
Emergency Reason: {emergency_reason}
Ambulance Unit  : {ambulance_id} (Status: EN ROUTE)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📍 LIVE GOOGLE MAPS NAVIGATION:
{maps_url}

Please keep your phone line active. First responders are on the way.
Emergency Helpline: 108 / 112

— AI Health Assistant Emergency Response Team"""
    return send_email(to_email, subject, message)

